data:
  image: busybox
  volumes:
    - /opt/www:/opt/www

php:
  build: images/php
  net: host
  ports:
    - "9000:9000"
  volumes_from:
    - data
  working_dir: /opt/www
  env_file: .env

node:
  build: images/node
  volumes_from:
    - data
  ports:
    - "3000:3000"
    - "6188:6188"
  net: host
  working_dir: /opt/www
  env_file: .env

mysql:
   build: images/mysql
   ports:
     - "3306:3306"
   volumes:
     - ./volumes/data/mysql:/var/lib/mysql
   env_file: .env

mongo:
   build: images/mongo
   ports:
     - "27017:27017"

ssdb:
   build: images/ssdb
   ports:
     - "16379:16379"
   env_file: .env

caddy:
   build: images/caddy
   volumes_from:
     - data
   working_dir: /opt/www
   ports:
     - "80:80"
     - "443:443"
     - "1988:1988"
     - "2015:2015"